# based on https://github.com/nfriedly/gmenunx/blob/ci/.github/workflows/c-cpp.yml
name: CI Build

on:
  push:
  pull_request:
  workflow_call:
    inputs:
      submodule:
        description: The directory of the submodule, if this workflow is being called on a submodule
        required: true
        type: string

jobs:   
  build-modern:
    name: MiyooCFW U-Boot (musl libc)
    runs-on: ubuntu-20.04
    container:
      image: nfriedly/miyoo-toolchain:latest
    steps:
    - uses: actions/checkout@v3
    # ARCH=arm and CROSS_COMPILE=arm-buildroot-linux-musleabi- env props are set in the docker image
    - name: configure
      run: |
        apt update && apt install -y libpython3-dev python3-distutils bison flex
        make miyoo_defconfig 
    - name: build
      run: make
    - uses: actions/upload-artifact@v3
      with:
        name: MiyooCFW U-Boot
        path: u-boot-sunxi-with-spl.bin
        if-no-files-found: error # 'error', 'warn', 'ignore'; defaults to `warn`

  build-legacy:
    name: Legacy MiyooCFW U-Boot (uClibc)
    runs-on: ubuntu-20.04
    container:
      image: nfriedly/miyoo-toolchain:steward
    steps:
    - uses: actions/checkout@v3
    # ARCH=arm and CROSS_COMPILE=arm-miyoo-linux-uclibcgnueabi- env props are set in the docker image
    - name: configure
      run: |
        apt update && apt install -y libpython3-dev python3-distutils
        make miyoo_defconfig 
    - name: build
      run: make
    - uses: actions/upload-artifact@v3
      with:
        name: Legacy MiyooCFW U-Boot
        path: u-boot-sunxi-with-spl.bin
        if-no-files-found: error # 'error', 'warn', 'ignore'; defaults to `warn`
